const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, PageNumber, PageBreak, LevelFormat, TableOfContents
} = require("docx");

// Fonts
const BW = "Times New Roman", BE = "宋体", HW = "Arial", HE = "黑体";
const bodyFont = { eastAsia: BE, ascii: BW, hAnsi: BW };
const headFont = { eastAsia: HE, ascii: HW, hAnsi: HW };
const R  = (t, o={}) => new TextRun(Object.assign({text:t, size:24, font:bodyFont}, o));
const B  = R; // 正文不加粗
const RH = (t, o={}) => new TextRun(Object.assign({text:t, font:headFont}, o));
const RC = (t)      => new TextRun({text:t, font:"Consolas", size:18});

const bdr = { style: BorderStyle.SINGLE, size: 1, color: "000000" };
const bdrs = { top: bdr, bottom: bdr, left: bdr, right: bdr };
const cm = { top: 50, bottom: 50, left: 80, right: 80 };

// Body paragraph: 段前段后0, 行距1.5, 首行缩进2字符
function P(content, opts={}) {
  const runs = typeof content==="string" ? [R(content)] : content.map(c=>typeof c==="string"?R(c):c);
  return new Paragraph({
    spacing: Object.assign({after:0,before:0,line:360,lineRule:"auto"}, opts.spacing||{}),
    indent: opts.indent===false ? {} : {firstLine:480},
    alignment: opts.alignment||undefined,
    children: runs
  });
}
function CL(text) {
  return new Paragraph({ spacing:{after:0,before:0,line:260}, shading:{fill:"F0F0F0",type:ShadingType.CLEAR}, indent:{left:240}, children:[RC(text)] });
}
function H1(text) { return new Paragraph({ heading:HeadingLevel.HEADING_1, spacing:{before:240,after:240}, alignment:AlignmentType.CENTER, children:[RH(text,{bold:true,size:32})] }); }
function H2(text) { return new Paragraph({ heading:HeadingLevel.HEADING_2, spacing:{before:120,after:120}, children:[RH(text,{bold:true,size:28})] }); }
function H3(text) { return new Paragraph({ heading:HeadingLevel.HEADING_3, spacing:{before:60,after:60}, children:[RH(text,{bold:true,size:24})] }); }
function Bul(text) { return new Paragraph({ numbering:{reference:"bullets",level:0}, spacing:{after:0,before:0,line:360}, children:[R(text)] }); }
function E() { return new Paragraph({ spacing:{after:0,before:0,line:360}, children:[] }); }
function TCaption(text) { return new Paragraph({ alignment:AlignmentType.CENTER, spacing:{before:160,after:60}, children:[new TextRun({text,size:20,bold:true,font:headFont})] }); }

function Cell(text, opts={}) {
  return new TableCell({ bdrs, margins:cm, width:{size:opts.w||2000,type:WidthType.DXA},
    shading: opts.s ? {fill:opts.s,type:ShadingType.CLEAR} : undefined, verticalAlign:"center",
    children:[new Paragraph({ spacing:{after:0,before:0}, alignment:opts.a||(opts.s?AlignmentType.CENTER:AlignmentType.LEFT),
      children:[new TextRun({text,size:20,bold:!!opts.b,font:opts.s?headFont:bodyFont})] })]
  });
}
function Row(cells, w, s) { return new TableRow({ children: cells.map((c,i)=>Cell(c,{w:w[i],s,b:s==="D9E2F3"&&i===0})) }); }

function coverLine(label, value) {
  return [new Paragraph({ indent:{left:720,firstLine:562}, spacing:{after:60,line:480},
    children:[ new TextRun({text:label+"：",bold:true,size:28,font:{eastAsia:HE}}),
              new TextRun({text:value,size:28,font:{eastAsia:HE},underline:{type:"single"}}) ]
  })];
}

const T = "员工管理系统的设计与实现";

const doc = new Document({
  styles: {
    default: { document: {
      run: {size:24,font:bodyFont},
      paragraph: {spacing:{after:0,before:0,line:360,lineRule:"auto"}}
    }},
    paragraphStyles: [
      {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:32,bold:true,font:headFont}, paragraph:{spacing:{before:240,after:240},outlineLevel:0,alignment:AlignmentType.CENTER}},
      {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:28,bold:true,font:headFont}, paragraph:{spacing:{before:120,after:120},outlineLevel:1}},
      {id:"Heading3",name:"Heading 3",basedOn:"Normal",next:"Normal",quickFormat:true,
        run:{size:24,bold:true,font:headFont}, paragraph:{spacing:{before:60,after:60},outlineLevel:2}},
    ]
  },
  numbering: { config: [
    {reference:"bullets",levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]},
  ]},
  sections: [
    // ===== COVER =====
    { properties:{page:{size:{width:11906,height:16838},margin:{top:1331,right:1134,bottom:1134,left:1418}}},
      children:[
        E(),E(),E(),
        new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:80},children:[new TextRun({text:"软 件 学 院",bold:true,size:78,font:"隶书"})]}),
        E(),
        new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:60},children:[new TextRun({text:"实践环节报告",bold:true,size:84,font:"隶书"})]}),
        E(),E(),E(),E(),E(),E(),
        ...coverLine("课程名称","软件开发实践一"),
        ...coverLine("课题名称",T),
        ...coverLine("专    业","软件工程"),
        ...coverLine("班    级","RB软工融253"),
        ...coverLine("学    号","202532044314"),
        ...coverLine("学生姓名","马康博"),
        ...coverLine("指导教师","王海龙"),
        E(),E(),
        new Paragraph({alignment:AlignmentType.CENTER,children:[
          new TextRun({text:"2026",size:28,bold:true}),new TextRun({text:"年",size:28,bold:true}),
          new TextRun({text:"7",size:28,bold:true}),new TextRun({text:"月",size:28,bold:true}),
          new TextRun({text:"3",size:28,bold:true}),new TextRun({text:"日",size:28,bold:true}),
        ]}),
      ]
    },
    // ===== BODY =====
    { properties:{page:{size:{width:11906,height:16838},margin:{top:1418,right:1134,bottom:1134,left:1418}}},
      headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"中原工学院软件学院  软件开发实践一设计任务书",size:18,color:"888888"})]})]})},
      footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"第 ",size:18}),new TextRun({children:[PageNumber.CURRENT],size:18}),new TextRun({text:" 页",size:18})]})]})},
      children:[
        // 任务书
        new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:100,after:100},children:[new TextRun({text:"中原工学院软件学院",bold:true,size:32})]}),
        new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:300},children:[new TextRun({text:"软件开发实践一设计任务书",bold:true,size:44})]}),
        new Table({ width:{size:9350,type:WidthType.DXA}, columnWidths:[933,1769,6648], rows:[
          Row(["姓 名","马康博","软件工程  专业  RB软工融253  班"],[933,1769,6648],"F2F2F2"),
          Row(["题 目","",T],[933,1769,6648],"F2F2F2"),
          new TableRow({height:{value:3700,rule:"atLeast"},children:[
            Cell("设\n计\n任\n务",{w:933,s:"F2F2F2",b:true}),
            new TableCell({bdrs,margins:cm,columnSpan:2,width:{size:8417,type:WidthType.DXA},children:[
              P([R("设计开发一个员工管理系统，主要功能包括：员工信息的增删改查、员工类型管理、员工信息统计。系统采用Java控制台应用形式，使用JDBC连接MySQL数据库，采用DAO设计模式实现数据访问分层架构。")],{indent:true}),
              P([R("1. 设计数据库表结构（emp员工表、emp_type员工类型表），建立外键关联")],{indent:true}),
              P([R("2. 实现DAO泛型接口及JDBC实现类，完成数据库CRUD操作")],{indent:true}),
              P([R("3. 实现Service业务层和Menu菜单层，完成用户交互界面")],{indent:true}),
              P([R("4. 实现系统主控制层（EmpSystem），整合各模块形成完整系统")],{indent:true}),
              P([R("（独立完成）")],{indent:true}),
              P([R("开发工具：IntelliJ IDEA、JDK 25、Maven、MySQL 8.0")],{indent:true}),
            ]})
          ]}),
          new TableRow({height:{value:2800,rule:"atLeast"},children:[
            Cell("时\n间\n进\n度",{w:933,s:"F2F2F2",b:true}),
            new TableCell({bdrs,margins:cm,columnSpan:2,width:{size:8417,type:WidthType.DXA},children:[
              P([R("第1周（2026-06-22~2026-06-26）：完成员工管理系统需求分析、系统分析与设计、数据库设计与实现等，完成DAO模式对数据库代码的编写。")],{indent:true}),
              P([R("第2周（2026年6月29日~2026年7月3日）：完成了多层模式中Service代码的编写，完成了Menu菜单的编写，完成了对员工管理系统的功能测试。")],{indent:true}),
            ]})
          ]}),
          new TableRow({height:{value:3200,rule:"atLeast"},children:[
            Cell("原 始 要\n参 考 资\n料 与 文\n    献",{w:933,s:"F2F2F2",b:true}),
            new TableCell({bdrs,margins:cm,columnSpan:2,width:{size:8417,type:WidthType.DXA},children:[
              P([R("[01] 林信良. Java学习笔记 JDK9 [M]. 北京: 清华大学出版社, 2018.6")],{indent:false}),
              P([R("[02] 李辉. 数据库原理与应用基础(MySQL) [M]. 北京: 高等教育出版社, 2019.8")],{indent:false}),
              P([R("[03] 张帆等. Java范例开发大全 [M]. 北京: 清华大学出版社, 2010.6")],{indent:false}),
            ]})
          ]}),
        ]}),
        E(),
        P([new TextRun({text:"指导教师签字：                            ",bold:true,size:22}),new TextRun({text:"2026    年    7  月  3  日",bold:true,size:22})],{indent:true}),
        new Paragraph({children:[new PageBreak()]}),

        // 摘要
        H1("摘  要"), E(),
        P([R("本系统是一个基于Java控制台"), R("的员工管理系统，采用JDBC + MySQL"), R("技术栈实现数据的持久化存储。系统围绕企业员工管理的核心需求，实现了员工信息的增删改查（CRUD）、员工类型分类管理以及多维度数据统计功能。在架构设计上，采用DAO设计模式与分层架构（Entity实体层→DAO数据访问层→Service业务层→Menu菜单层→System控制层），通过泛型接口DAO<T>实现代码复用，降低了各模块之间的耦合度。系统使用Lombok简化实体类代码，使用PreparedStatement防止SQL注入。用户通过控制台菜单交互，操作直观简洁。")],{indent:true}),
        E(),
        P([new TextRun({text:"关键词：",bold:true,font:headFont}), R("Java；MySQL；JDBC；DAO设计模式；员工管理系统")],{indent:true}),
        new Paragraph({children:[new PageBreak()]}),

        // 目录
        new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:300},children:[new TextRun({text:"目  录",bold:true,size:36,font:headFont})]}),
        new TableOfContents("目录",{hyperlink:true,headingStyleRange:"1-3"}),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 第1章 ====================
        H1("第1章  需求分析"), E(),
        P("本系统旨在为企业人力资源管理部门提供一个轻量级的员工信息管理工具，能够在控制台环境下完成员工信息的录入、修改、删除、查询以及统计分析等日常操作，提高管理效率，降低人工管理的错误率。"),
        P("具体目标包括：①建立员工信息的电子化档案，替代传统的纸质或Excel管理方式；②通过员工类型分类，支持对不同类别员工的分组管理；③提供多维度统计功能，为管理人员提供数据决策支持。"),
        H2("1.1  功能需求"),
        H3("1.1.1  员工管理模块"),
        Bul("添加员工：录入员工姓名、电话、工号、地址、薪资，并选择所属类型"),
        Bul("删除员工：根据员工ID删除指定员工记录"),
        Bul("修改员工：根据员工ID更新员工的所有字段信息"),
        Bul("查询员工：支持按ID精确查询，支持分页查询全部员工"),
        Bul("工号唯一性校验：新增员工时自动检查工号是否重复"),
        Bul("工号自动生成：获取当前最大工号，辅助新增时自动编号"),
        H3("1.1.2  员工类型管理模块"),
        Bul("添加类型：新增员工类型（如\"经理\"\"职员\"\"实习生\"等）"),
        Bul("删除类型：删除指定类型（需校验该类型下是否有员工）"),
        Bul("修改类型：更新类型的名称"),
        Bul("查询类型：按ID查询单个类型，分页查询全部类型"),
        H3("1.1.3  统计功能模块"),
        Bul("统计员工总数、工资总额、平均薪资"),
        Bul("按员工类型分组统计工资总额"),
        Bul("按员工类型分组统计平均薪资"),
        H2("1.2  系统菜单结构"),
        P("系统采用三级菜单设计：主菜单（EmpSystem）→ 子菜单（EmpMenu/EmpTypeMenu/StatisMenu）→ 具体操作。管理员通过控制台输入数字选择功能，操作完成后可逐级返回。主菜单结构如下："),
        CL("=========================================="),
        CL("  欢迎使用员工管理系统"),
        CL("  1. 员工管理菜单"),
        CL("  2. 员工类型管理菜单"),
        CL("  3. 统计菜单"),
        CL("  0. 退出系统"),
        CL("=========================================="),
        E(),
        P("员工管理子菜单："),
        CL("  1. 添加员工    2. 删除员工    3. 修改员工"),
        CL("  4. 查询员工    5. 查询全部    0. 返回上级"),
        E(),
        P("统计子菜单："),
        CL("  1. 统计员工数量    2. 统计工资总额    3. 统计平均薪资"),
        CL("  4. 各类型工资总额  5. 各类型平均薪资  0. 返回上级"),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 第2章 ====================
        H1("第2章  系统设计"), E(),
        H2("2.1  系统分层架构"),
        P("本系统采用经典的分层架构设计，遵循\"高内聚、低耦合\"的原则，从上到下划分为五个层次："),
        E(),
        TCaption("表2-1  系统分层架构"),
        new Table({ width:{size:9026,type:WidthType.DXA}, columnWidths:[1800,2500,4726], rows:[
          Row(["层次","包路径","职责"],[1800,2500,4726],"D9E2F3"),
          Row(["实体层","entity","定义数据载体类（Emp、EmpType），使用Lombok注解自动生成getter/setter，与数据库表一一对应"],[1800,2500,4726],"FFFFFF"),
          Row(["数据访问层","dao + dao.impl","DAO<T>泛型接口定义CRUD契约；EmpDAO/EmpTypeDAO使用JDBC实现具体数据库操作"],[1800,2500,4726],"F2F6FC"),
          Row(["工具层","ds","DBConfig存储数据库连接配置；DBUtil封装Connection获取与资源释放"],[1800,2500,4726],"FFFFFF"),
          Row(["业务层","service","EmpService/EmpTypeService处理业务逻辑校验，调用DAO完成操作"],[1800,2500,4726],"F2F6FC"),
          Row(["表现层","menu + system","SysMenu为菜单基类（封装Scanner输入）；各Menu子类展示功能菜单；EmpSystem为系统主入口控制器"],[1800,2500,4726],"FFFFFF"),
        ]}),
        E(),
        P("Menu层采用继承体系：SysMenu作为抽象基类提供choice()方法获取用户输入，EmpSystem（主菜单）、EmpMenu（员工管理子菜单）、EmpTypeMenu（类型管理子菜单）、StatisMenu（统计子菜单）均继承自SysMenu，实现代码复用。"),
        P("接下来重点介绍菜单系统的实现。SysMenu作为所有菜单的基类，封装了java.util.Scanner对象用于接收用户输入，并提供protected方法choice()供子类调用："),
        E(),
        P([R("SysMenu.java —— 菜单基类：")]),
        CL("package org.example.menu;"),
        CL("import java.util.Scanner;"),
        CL(""),
        CL("public class SysMenu {"),
        CL("    protected Scanner scanner = new Scanner(System.in);"),
        CL("    protected int choice() {"),
        CL("        return scanner.nextInt();"),
        CL("    }"),
        CL("}"),
        E(),
        P("所有菜单类都继承自SysMenu，通过调用父类的choice()方法获取用户键盘输入。以下为系统主控制器EmpSystem的核心代码："),
        E(),
        P([R("EmpSystem.java —— 系统主入口（关键代码）：")]),
        CL("public class EmpSystem extends SysMenu {"),
        CL("    public void run() {"),
        CL("        int choice;"),
        CL("        while (true) {"),
        CL("            System.out.println(\"欢迎使用员工管理系统\");"),
        CL("            System.out.println(\"1. 员工管理菜单\");"),
        CL("            System.out.println(\"2. 员工类型管理菜单\");"),
        CL("            System.out.println(\"3. 统计菜单\");"),
        CL("            System.out.println(\"0. 退出系统\");"),
        CL("            choice = choice();    // 调用父类方法读取输入"),
        CL("            switch (choice) {"),
        CL("                case 0: System.exit(0);"),
        CL("                case 1: new EmpMenu().run(); break;"),
        CL("                case 2: new EmpTypeMenu().run(); break;"),
        CL("                case 3: new StatisMenu().run(); break;"),
        CL("            }"),
        CL("        }"),
        CL("    }"),
        CL("}"),
        E(),
        P("子菜单EmpMenu的结构与之类似，继承SysMenu后重写run()方法展示各自的选项列表，通过switch-case将用户选择分发到Service层完成具体操作。"),
        E(),
        P([R("EmpMenu.java —— 员工管理子菜单（关键代码）：")]),
        CL("public class EmpMenu extends SysMenu {"),
        CL("    private EmpService empService = new EmpService();"),
        CL("    public void run() {"),
        CL("        int i = 1;"),
        CL("        while (i != 0) {"),
        CL("            System.out.println(\"1. 添加员工\");"),
        CL("            System.out.println(\"2. 删除员工\");"),
        CL("            System.out.println(\"3. 修改员工\");"),
        CL("            System.out.println(\"0. 返回上级菜单\");"),
        CL("            i = choice();"),
        CL("            switch (i) {"),
        CL("                case 1: empService.addEmp(); break;"),
        CL("                case 2: empService.deleteEmp(); break;"),
        CL("                case 3: empService.updateEmp(); break;"),
        CL("                case 0: return;"),
        CL("            }"),
        CL("        }"),
        CL("    }"),
        CL("}"),
        new Paragraph({children:[new PageBreak()]}),

        H2("2.2  数据库设计"),
        H3("2.2.1  E-R图"),
        P("系统包含两个实体：员工（Emp）和员工类型（EmpType）。二者之间为多对一关系：一个员工类型下可以有多个员工，一个员工只能属于一种员工类型。"),
        E(),
        P([R("Emp —— emp_id（主键）、emp_name、emp_tel、emp_no、emp_addr、emp_salary、type_id（外键→EmpType.type_id）")],{indent:false}),
        P([R("EmpType —— type_id（主键）、type_name")],{indent:false}),
        E(),
        H3("2.2.2  数据表结构"),
        P("数据库名称：253254，字符集：UTF-8"),
        E(),
        TCaption("表2-2  emp表（员工信息表）"),
        new Table({ width:{size:9026,type:WidthType.DXA}, columnWidths:[2000,1500,1200,400,1200,2726], rows:[
          Row(["字段名","数据类型","长度","允许空","约束","说明"],[2000,1500,1200,400,1200,2726],"D9E2F3"),
          Row(["emp_id","INT","11","否","主键 自增","员工编号"],[2000,1500,1200,400,1200,2726],"FFFFFF"),
          Row(["emp_name","VARCHAR","50","否","","员工姓名"],[2000,1500,1200,400,1200,2726],"F2F6FC"),
          Row(["emp_tel","VARCHAR","20","是","","联系电话"],[2000,1500,1200,400,1200,2726],"FFFFFF"),
          Row(["emp_no","INT","11","否","","工号"],[2000,1500,1200,400,1200,2726],"F2F6FC"),
          Row(["emp_addr","VARCHAR","100","是","","地址"],[2000,1500,1200,400,1200,2726],"FFFFFF"),
          Row(["emp_salary","INT","11","是","","薪资"],[2000,1500,1200,400,1200,2726],"F2F6FC"),
          Row(["type_id","INT","11","是","外键","员工类型ID"],[2000,1500,1200,400,1200,2726],"FFFFFF"),
        ]}),
        E(),
        TCaption("表2-3  emp_type表（员工类型表）"),
        new Table({ width:{size:9026,type:WidthType.DXA}, columnWidths:[2000,1500,1200,400,1200,2726], rows:[
          Row(["字段名","数据类型","长度","允许空","约束","说明"],[2000,1500,1200,400,1200,2726],"D9E2F3"),
          Row(["type_id","INT","11","否","主键 自增","类型编号"],[2000,1500,1200,400,1200,2726],"FFFFFF"),
          Row(["type_name","VARCHAR","50","否","","类型名称"],[2000,1500,1200,400,1200,2726],"F2F6FC"),
        ]}),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 第3章 ====================
        H1("第3章  系统实现"), E(),
        H2("3.1  JDBC数据库连接技术"),
        P("系统使用JDBC（Java Database Connectivity）作为Java与MySQL数据库之间的桥梁。操作数据库遵循标准的五步流程：加载驱动→获取连接→创建语句→执行→释放资源。"),
        E(),
        TCaption("表3-1  JDBC五步流程"),
        new Table({ width:{size:9026,type:WidthType.DXA}, columnWidths:[1000,1500,2880,3646], rows:[
          Row(["步骤","关键词","对应代码","说明"],[1000,1500,2880,3646],"D9E2F3"),
          Row(["1","加载驱动","Class.forName(...)","注册MySQL驱动"],[1000,1500,2880,3646],"FFFFFF"),
          Row(["2","获取连接","DriverManager.getConnection(...)","建立TCP连接到MySQL"],[1000,1500,2880,3646],"F2F6FC"),
          Row(["3","创建语句","conn.prepareStatement(sql)","预编译SQL防注入"],[1000,1500,2880,3646],"FFFFFF"),
          Row(["4","执行SQL","executeUpdate()/executeQuery()","增删改/查询"],[1000,1500,2880,3646],"F2F6FC"),
          Row(["5","释放资源","try-with-resources","自动关闭资源"],[1000,1500,2880,3646],"FFFFFF"),
        ]}),
        E(),
        P("DBUtil工具类封装了连接获取和释放："),
        E(),
        P([R("DBConfig.java —— 数据库配置：")]),
        CL("public interface DBConfig {"),
        CL("    String URL = \"jdbc:mysql://localhost:3306/253254\";"),
        CL("    String USER = \"root\";"),
        CL("    String PASSWORD = \"****\";"),
        CL("}"),
        E(),
        P([R("DBUtil.java —— 连接工具类：")]),
        CL("public class DBUtil {"),
        CL("    public static Connection getConnection() throws Exception {"),
        CL("        return DriverManager.getConnection("),
        CL("            DBConfig.URL, DBConfig.USER, DBConfig.PASSWORD);"),
        CL("    }"),
        CL("    public static void close(Connection conn) throws Exception {"),
        CL("        if (conn != null) { conn.close(); }"),
        CL("    }"),
        CL("}"),
        E(),
        P("系统全面使用PreparedStatement预编译语句，有效防止SQL注入攻击。以下为EmpDAO中add方法的实现，展示了完整的JDBC操作流程："),
        E(),
        P([R("EmpDAO.add() —— 添加员工（关键代码）：")]),
        CL("public int add(Emp emp) throws Exception {"),
        CL("    conn = DBUtil.getConnection();"),
        CL("    String sql = \"INSERT INTO `emp`(emp_name,emp_tel,emp_no,\""),
        CL("               + \"emp_addr,emp_salary,type_id) VALUES (?,?,?,?,?,?)\";"),
        CL("    PreparedStatement pstmt = conn.prepareStatement(sql);"),
        CL("    pstmt.setString(1, emp.getEmpName());"),
        CL("    pstmt.setString(2, emp.getEmpTel());"),
        CL("    pstmt.setInt(3, emp.getEmpNo());"),
        CL("    pstmt.setString(4, emp.getEmpAddr());"),
        CL("    pstmt.setInt(5, emp.getEmpSalary());"),
        CL("    pstmt.setInt(6, emp.getTypeId());"),
        CL("    int i = pstmt.executeUpdate();"),
        CL("    DBUtil.close(conn);"),
        CL("    return i;"),
        CL("}"),
        E(),
        P("上述代码中，SQL语句使用?占位符代替直接拼接字符串，通过setString()/setInt()方法安全地绑定参数，从根本上防止了SQL注入攻击。"),

        H2("3.2  DAO设计模式"),
        P("系统定义了一个泛型接口DAO<T>，作为所有数据访问对象的统一契约。通过泛型参数<T>，同一个接口可以被Emp及EmpType两个实体类复用："),
        E(),
        P([R("DAO.java —— 泛型数据访问接口：")]),
        CL("public interface DAO<T> {"),
        CL("    int add(T t) throws Exception;"),
        CL("    int delete(int id) throws Exception;"),
        CL("    int update(T t) throws Exception;"),
        CL("    T queryById(int id) throws Exception;"),
        CL("    List<T> queryAll(int pageNum, int pageSize) throws Exception;"),
        CL("}"),
        E(),
        P("EmpDAO实现了DAO<Emp>，针对emp表提供完整的CRUD操作。除接口定义的5个方法外，还扩展了findAll()、checkEmpNo()、getMaxEmpNo()等辅助方法。"),
        new Paragraph({children:[new PageBreak()]}),

        H2("3.3  程序入口与启动流程"),
        P("整个系统的入口类为Test.java，通过创建EmpSystem实例并调用run()方法启动系统："),
        E(),
        P([R("Test.java —— 系统启动入口：")]),
        CL("public class Test {"),
        CL("    public static void main(String[] args) {"),
        CL("        EmpSystem system = new EmpSystem();"),
        CL("        system.run();"),
        CL("    }"),
        CL("}"),
        E(),
        P("调用链路为：Test.main() → EmpSystem.run()（主菜单）→ EmpMenu/EmpTypeMenu/StatisMenu.run()（子菜单）→ EmpService/EmpTypeService → EmpDAO/EmpTypeDAO → DBUtil → MySQL。层层传递，每层职责明确。"),
        E(),
        P([R("实体类示例——Emp.java（使用Lombok注解）：")]),
        CL("@Data @NoArgsConstructor @AllArgsConstructor"),
        CL("public class Emp {"),
        CL("    private Integer empId;"),
        CL("    private String empName;"),
        CL("    private String empTel;"),
        CL("    private Integer empNo;"),
        CL("    private String empAddr;"),
        CL("    private Integer empSalary;"),
        CL("    private Integer typeId;    // 外键,关联emp_type表"),
        CL("}"),
        E(),
        P("通过@Data注解，Lombok自动生成了getter/setter/toString/equals/hashCode方法，加上@NoArgsConstructor和@AllArgsConstructor生成构造方法，原本需要100+行的手写代码缩减为约10行。"),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 第4章 结束语 ====================
        H1("第4章  结束语"), E(),
        P("通过本次软件开发实践，我完成了一个完整的员工管理系统，从需求分析、数据库设计到编码实现和功能测试，完整地体验了软件开发的各个阶段。主要收获："),
        E(),
        P([R("1. 掌握了JDBC数据库编程技术。通过实践深入理解了JDBC五步流程、PreparedStatement预编译语句的使用、ResultSet结果集的处理。")],{indent:true}),
        P([R("2. 理解了分层架构和DAO设计模式。通过将系统划分为entity、dao、ds、service、menu等多个层次，体会到\"高内聚、低耦合\"的架构优势。")],{indent:true}),
        P([R("3. 掌握了面向对象编程的核心思想。从继承（SysMenu基类体系）、泛型（DAO<T>）、接口（面向接口编程）到Lombok注解，在实践中巩固了Java面向对象的各项关键技术。")],{indent:true}),
        P([R("4. 提升了问题分析与解决能力。在开发过程中遇到数据库连接失败、SQL语法错误、资源泄漏等问题，通过查阅资料和调试逐步解决。")],{indent:true}),
        E(),
        P("同时，本系统也存在一些不足：目前仅支持控制台操作界面，后续可以考虑增加Web界面；Service层的业务逻辑校验还不够完善；系统中尚未实现事务管理机制。这些都是在今后学习中需要继续深入的方向。"),
        P("总之，本次实践课题让我将课堂所学的Java基础知识、数据库原理和软件工程方法综合运用到了实际项目中，加深了对软件开发全流程的理解，为今后的学习和职业发展打下了坚实的基础。"),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 参考文献 ====================
        H1("参考文献"), E(),
        P("[01] 林信良. Java学习笔记 JDK9 [M]. 北京: 清华大学出版社, 2018.6"),
        P("[02] 李辉. 数据库原理与应用基础(MySQL) [M]. 北京: 高等教育出版社, 2019.8"),
        P("[03] 张帆等. Java范例开发大全 [M]. 北京: 清华大学出版社, 2010.6"),
        new Paragraph({children:[new PageBreak()]}),

        // ==================== 附录 ====================
        H1("附录  关键源代码"), E(),
        P("附录列出系统的关键功能代码，按层次排列。"), E(),

        H2("一、实体层"), E(),
        CL("@Data"),
        CL("@NoArgsConstructor"),
        CL("@AllArgsConstructor"),
        CL("public class Emp {"),
        CL("    private Integer empId;"),
        CL("    private String empName;"),
        CL("    private String empTel;"),
        CL("    private Integer empNo;"),
        CL("    private String empAddr;"),
        CL("    private Integer empSalary;"),
        CL("    private Integer typeId;"),
        CL("}"),
        E(),
        CL("@Data"),
        CL("@NoArgsConstructor"),
        CL("@AllArgsConstructor"),
        CL("public class EmpType {"),
        CL("    private Integer typeId;"),
        CL("    private String typeName;"),
        CL("}"),
        E(),

        H2("二、数据访问层"), E(),
        CL("public interface DAO<T> {"),
        CL("    int add(T t) throws Exception;"),
        CL("    int delete(int id) throws Exception;"),
        CL("    int update(T t) throws Exception;"),
        CL("    T queryById(int id) throws Exception;"),
        CL("    List<T> queryAll(int pageNum, int pageSize) throws Exception;"),
        CL("}"),
        E(),
        CL("public class EmpDAO implements DAO<Emp> {"),
        CL("    private Connection conn;"),
        CL(""),
        CL("    @Override"),
        CL("    public int add(Emp emp) throws Exception {"),
        CL("        conn = DBUtil.getConnection();"),
        CL("        String sql = \"INSERT INTO `emp`(emp_name,emp_tel,\""),
        CL("                   + \"emp_no,emp_addr,emp_salary,type_id)\""),
        CL("                   + \" VALUES (?,?,?,?,?,?)\";"),
        CL("        PreparedStatement pstmt = conn.prepareStatement(sql);"),
        CL("        pstmt.setString(1, emp.getEmpName());"),
        CL("        pstmt.setString(2, emp.getEmpTel());"),
        CL("        pstmt.setInt(3, emp.getEmpNo());"),
        CL("        pstmt.setString(4, emp.getEmpAddr());"),
        CL("        pstmt.setInt(5, emp.getEmpSalary());"),
        CL("        pstmt.setInt(6, emp.getTypeId());"),
        CL("        int i = pstmt.executeUpdate();"),
        CL("        DBUtil.close(conn);"),
        CL("        return i;"),
        CL("    }"),
        CL(""),
        CL("    @Override"),
        CL("    public Emp queryById(int id) throws Exception {"),
        CL("        conn = DBUtil.getConnection();"),
        CL("        String sql = \"select * from emp where emp_id = ?\";"),
        CL("        PreparedStatement pstmt = conn.prepareStatement(sql);"),
        CL("        pstmt.setInt(1, id);"),
        CL("        ResultSet rs = pstmt.executeQuery();"),
        CL("        Emp emp = null;"),
        CL("        if (rs.next()) {"),
        CL("            emp = new Emp();"),
        CL("            emp.setEmpId(rs.getInt(\"emp_id\"));"),
        CL("            emp.setEmpName(rs.getString(\"emp_name\"));"),
        CL("            emp.setEmpTel(rs.getString(\"emp_tel\"));"),
        CL("            emp.setEmpNo(rs.getInt(\"emp_no\"));"),
        CL("            emp.setEmpAddr(rs.getString(\"emp_addr\"));"),
        CL("            emp.setEmpSalary(rs.getInt(\"emp_salary\"));"),
        CL("            emp.setTypeId(rs.getInt(\"type_id\"));"),
        CL("        }"),
        CL("        DBUtil.close(conn);"),
        CL("        return emp;"),
        CL("    }"),
        CL(""),
        CL("    @Override"),
        CL("    public List<Emp> queryAll(int pageNum, int pageSize)"),
        CL("            throws Exception {"),
        CL("        conn = DBUtil.getConnection();"),
        CL("        String sql = \"select * from emp limit ?,?\";"),
        CL("        PreparedStatement pstmt = conn.prepareStatement(sql);"),
        CL("        pstmt.setInt(1, (pageNum - 1) * pageSize);"),
        CL("        pstmt.setInt(2, pageSize);"),
        CL("        ResultSet rs = pstmt.executeQuery();"),
        CL("        List<Emp> list = new ArrayList<>();"),
        CL("        while (rs.next()) {"),
        CL("            Emp emp = new Emp(rs.getInt(1),rs.getString(2),"),
        CL("                rs.getString(3),rs.getInt(4),rs.getString(5),"),
        CL("                rs.getInt(6),rs.getInt(7));"),
        CL("            list.add(emp);"),
        CL("        }"),
        CL("        DBUtil.close(conn);"),
        CL("        return list;"),
        CL("    }"),
        CL(""),
        CL("    public boolean checkEmpNo(int empNo) throws Exception {"),
        CL("        conn = DBUtil.getConnection();"),
        CL("        String sql = \"select count(*) from emp where emp_no = ?\";"),
        CL("        PreparedStatement pstmt = conn.prepareStatement(sql);"),
        CL("        pstmt.setInt(1, empNo);"),
        CL("        ResultSet rs = pstmt.executeQuery();"),
        CL("        if (rs.next()) {"),
        CL("            boolean exists = rs.getInt(1) > 0;"),
        CL("            DBUtil.close(conn);"),
        CL("            return exists;"),
        CL("        }"),
        CL("        DBUtil.close(conn);"),
        CL("        return false;"),
        CL("    }"),
        CL("}"),
        new Paragraph({children:[new PageBreak()]}),

        H2("三、工具层"), E(),
        CL("public interface DBConfig {"),
        CL("    String URL = \"jdbc:mysql://localhost:3306/253254\";"),
        CL("    String USER = \"root\";"),
        CL("    String PASSWORD = \"****\";"),
        CL("}"),
        E(),
        CL("public class DBUtil {"),
        CL("    public static Connection getConnection() throws Exception {"),
        CL("        return DriverManager.getConnection("),
        CL("            DBConfig.URL, DBConfig.USER, DBConfig.PASSWORD);"),
        CL("    }"),
        CL(""),
        CL("    public static void close(Connection conn) throws Exception {"),
        CL("        if (conn != null) { conn.close(); }"),
        CL("    }"),
        CL("}"),
        E(),

        H2("四、菜单层"), E(),
        CL("public class SysMenu {"),
        CL("    protected Scanner scanner = new Scanner(System.in);"),
        CL("    protected int choice() { return scanner.nextInt(); }"),
        CL("}"),
        E(),
        CL("public class EmpSystem extends SysMenu {"),
        CL("    public void run() {"),
        CL("        int choice;"),
        CL("        while (true) {"),
        CL("            System.out.println(\"1.员工管理 2.类型管理 3.统计 0.退出\");"),
        CL("            choice = choice();"),
        CL("            switch (choice) {"),
        CL("                case 0: System.exit(0);"),
        CL("                case 1: new EmpMenu().run(); break;"),
        CL("                case 2: new EmpTypeMenu().run(); break;"),
        CL("                case 3: new StatisMenu().run(); break;"),
        CL("            }"),
        CL("        }"),
        CL("    }"),
        CL("}"),
        E(),
        CL("public class EmpMenu extends SysMenu {"),
        CL("    private EmpService empService = new EmpService();"),
        CL("    public void run() {"),
        CL("        int i = 1;"),
        CL("        while (i != 0) {"),
        CL("            System.out.println(\"1.添加 2.删除 3.修改 0.返回\");"),
        CL("            i = choice();"),
        CL("            switch (i) {"),
        CL("                case 1: empService.addEmp(); break;"),
        CL("                case 2: empService.deleteEmp(); break;"),
        CL("                case 3: empService.updateEmp(); break;"),
        CL("                case 0: return;"),
        CL("            }"),
        CL("        }"),
        CL("    }"),
        CL("}"),
        E(),

        H2("五、程序入口"), E(),
        CL("public class Test {"),
        CL("    public static void main(String[] args) {"),
        CL("        EmpSystem system = new EmpSystem();"),
        CL("        system.run();"),
        CL("    }"),
        CL("}"),
      ]
    }
  ]
});

const out = "E:\\我的桌面\\课程设计报告.docx";
Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync(out, buf);
  console.log("OK: " + out + " (" + buf.length + " bytes)");
});
